In [15]:
import pandas as pd

5 DATASETS.
1. top 250 series valoradas en imdb (250 rows × 5 columns)
2. top 250 peliculas valoradas en imdb (250 rows × 8 columns)
3. Contenido disponible en Netflix (8807 rows × 12 columns)
4. Contenido disponible en Amazon Prime Video (9668 rows × 12 columns)
5. Contenido disponible en HBO (7342 rows × 8 columns)

In [17]:
df_top_series=pd.read_csv("./Data/imdb_Top_250_TV_Shows.csv")

In [18]:
df_top_series

,Shows Name,Release Year,Episodes,Rating,Rating given by people
0,Breaking Bad,2008–2013,62 eps,9.5,(2.2M)
1,Planet Earth II,2016,6 eps,9.5,(163K)
2,Planet Earth,2006,11 eps,9.4,(224K)
3,Band of Brothers,2001,10 eps,9.4,(547K)
4,Chernobyl,2019,5 eps,9.3,(912K)
...,...,...,...,...,...
245,Umbre,2014–2019,21 eps,8.7,(12K)
246,Foyle's War,2002–2015,28 eps,8.6,(19K)
247,Gintama,2005–2021,375 eps,8.7,(17K)
248,The Great British Baking Show,2010–,189 eps,8.6,(13K)
249,Community,2009–2015,110 eps,8.5,(300K)

In [23]:
df_top_movies=(pd.read_csv("./Data/imdb_top_250_movies.csv",encoding='latin1'))

In [24]:
df_top_movies

,Title,Release_year,Duration,Duration_in_minutes,Rating,Content_rating,No_of_votes,No_of_votes_numeric
0,The Shawshank Redemption,1994,2h 22m,142,9.3,R,3M,3000000
1,The Godfather,1972,2h 55m,175,9.2,R,2.1M,2100000
2,The Dark Knight,2008,2h 32m,152,9.0,PG-13,3M,3000000
3,The Godfather Part II,1974,3h 22m,202,9.0,R,1.4M,1400000
4,12 Angry Men,1957,1h 36m,96,9.0,Approved,898K,898000
...,...,...,...,...,...,...,...,...
245,Amores Perros,2000,2h 34m,154,8.0,R,257K,257000
246,Rebecca,1940,2h 10m,130,8.1,Approved,150K,150000
247,The Help,2011,2h 26m,146,8.1,PG-13,504K,504000
248,A Silent Voice: The Movie,2016,2h 10m,130,8.1,Not Rated,110K,110000
249,Cool Hand Luke,1967,2h 7m,127,8.0,Approved,192K,192000

In [25]:
df_netflix=pd.read_csv("./Data/netflix_titles.csv")

In [26]:
df_netflix

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [27]:
df_amazon=pd.read_csv("./Data/amazon_prime_titles.csv")

In [28]:
df_amazon

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [29]:
df_hbo=pd.read_csv("./Data/hbo_titles.csv")

In [30]:
df_hbo

,title,type,genres,releaseYear,imdbId,imdbAverageRating,imdbNumVotes,availableCountries
0,The Fifth Element,movie,"Action, Adventure, Sci-Fi",1997.0,tt0119116,7.6,518745.0,"DK, FI, NO, SE"
1,Jarhead,movie,"Biography, Drama, War",2005.0,tt0418763,7.0,212483.0,"HK, MY, PH, SG, TW"
2,Unforgiven,movie,"Drama, Western",1992.0,tt0105695,8.2,445916.0,"AG, AR, BB, BE, BO, BR, BS, BZ, CL, CO, CR, DO..."
3,Eternal Sunshine of the Spotless Mind,movie,"Drama, Romance, Sci-Fi",2004.0,tt0338013,8.3,1111333.0,"AG, AR, BB, BO, BS, BZ, CL, CO, CR, DO, EC, GT..."
4,A History of Violence,movie,"Action, Crime, Drama",2005.0,tt0399146,7.4,259993.0,"AG, AR, BB, BO, BR, BS, BZ, CL, CO, CR, DO, EC..."
...,...,...,...,...,...,...,...,...
7337,Girl Scout Cookie Championship,tv,Reality-TV,2020.0,tt11091964,4.9,10.0,"AG, AR, BB, BO, BR, BS, BZ, CL, CO, CR, DO, EC..."
7338,An American Story,tv,Reality-TV,2021.0,tt15447994,NaN,NaN,"AG, AR, BB, BO, BR, BS, BZ, CL, CO, CR, DO, EC..."
7339,NaN,tv,Reality,2010.0,NaN,NaN,NaN,"AG, AR, BB, BO, BR, BS, BZ, CL, CO, CR, DO, EC..."
7340,7 Chances Para,tv,Comedy,2022.0,tt19514840,8.7,7.0,"AR, BO, BR, CL, CO, CR, DO, EC, GT, HN, MX, NI..."
7341,Luva de Pedreiro: O Rei da Jogada,tv,"Documentary, Sport",2024.0,tt34530164,7.0,10.0,"AG, AR, BB, BO, BR, BS, BZ, CL, CO, CR, DO, EC..."